version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s %(levelname)-8s %(name)s  - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  rasa:
    level: INFO
  h5py:
    level: ERROR
  tensorflow:
    level: ERROR
  urllib3:
    level: ERROR

root:
  level: INFO
  handlers: [console]
